"""Export a RetroReport to Markdown and self-contained HTML.

Mirrors the standup exporter (standup/export.py): readable artifacts written
under ``~/.scrum-agent/exports/retro/<project>/`` so a retro's outcome persists
as a shareable document, not just in the logs. The TUI **Export** button writes
the current board on demand.

Every card ``text`` / ``author`` is attacker-influenced (any LAN participant
added it), so the HTML escapes every field with ``html.escape`` — the same
defense the standup exporter uses. The HTML reuses the plan report's stylesheet
(``html_exporter._CSS``) so retro pages look consistent with the rest of the app.

# See README: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from html import escape as _e
from pathlib import Path

from yeaboi.agent.state import RetroReport
from yeaboi.retro.board import CARRIED_STATUS_LABELS, RETRO_GRID_LABELS, RETRO_GRIDS

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "retro"


def _title(report: RetroReport) -> str:
    sprint = f" — {report.sprint_name}" if report.sprint_name else ""
    return f"Sprint Retro{sprint}"


def _reactions_str(card) -> str:
    """Render a card's reaction counts as ``👍 3 ❤️ 1`` (empty if none)."""
    return "  ".join(f"{emoji} {count}" for emoji, count in card.reactions if count)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_retro_markdown(report: RetroReport) -> str:
    """Return the retro as a Markdown document."""
    by_grid = report.by_grid()
    lines: list[str] = [
        f"# {_title(report)}",
        "",
        f"**Date:** {report.date}  ",
        f"**Participants:** {', '.join(report.participants) if report.participants else '—'}",
        "",
    ]
    from yeaboi.markdown_convert import md_table_cell as _cell

    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        lines.append(f"## {RETRO_GRID_LABELS[grid]}")
        lines.append("")
        if not cards:
            lines += ["_No cards._", ""]
            continue
        if grid == "action_items":
            # Action items are to-dos — checkboxes become native task lists
            # on Notion (to_do) and Confluence (<ac:task-list>).
            for c in cards:
                tag = " _(AI)_" if c.origin == "ai" else (f" — _{c.author}_" if c.author else "")
                lines.append(f"- [ ] {c.text}{tag}")
        else:
            # Card grids read best as a table (author + reactions alongside).
            lines += ["| Card | By | Reactions |", "|------|----|-----------|"]
            for c in cards:
                by = "_(AI)_" if c.origin == "ai" else (_cell(c.author) if c.author else "—")
                rx = _reactions_str(c) or "—"
                lines.append(f"| {_cell(c.text)} | {by} | {rx} |")
        lines.append("")

    # Last sprint's action items + the progress the team recorded this retro.
    if report.carried_action_items:
        lines += ["## Last sprint's action items — progress", ""]
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            lines.append(f"- **[{status}]** {_cell(c.text)}")
        lines.append("")

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines += ["---", "", f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {ts}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def build_retro_html(report: RetroReport) -> str:
    """Return the retro as a self-contained HTML document (reuses the plan CSS)."""
    from yeaboi.html_exporter import _CSS

    by_grid = report.by_grid()
    date_span = f"<span style='color:var(--text-muted);font-weight:400'>&mdash; {_e(report.date)}</span>"
    parts: list[str] = [
        '<div class="container">',
        f"<h1>{_e(_title(report))} {date_span}</h1>",
        (
            "<p><strong>Participants:</strong> "
            f"{_e(', '.join(report.participants)) if report.participants else '&mdash;'}</p>"
        ),
        # Two-column responsive grid of the four retro columns.
        "<div style='display:grid;grid-template-columns:repeat(2,1fr);gap:1rem'>",
    ]
    for grid in RETRO_GRIDS:
        cards = by_grid.get(grid, [])
        parts.append(
            "<div style='border:1px solid var(--border,#30363d);border-radius:8px;padding:.8rem 1rem'>"
            f"<h2 style='margin-top:0'>{_e(RETRO_GRID_LABELS[grid])}</h2>"
        )
        if cards:
            parts.append("<ul style='margin:0;padding-left:1.1rem'>")
            for c in cards:
                if c.origin == "ai":
                    tag = " <em style='color:var(--text-muted)'>(AI)</em>"
                elif c.author:
                    tag = f" <em style='color:var(--text-muted)'>— {_e(c.author)}</em>"
                else:
                    tag = ""
                rx = _reactions_str(c)
                # Reaction emojis are from a fixed set, but escape defensively anyway.
                rx_html = f" <span style='color:var(--text-muted)'>{_e(rx)}</span>" if rx else ""
                parts.append(f"<li>{_e(c.text)}{tag}{rx_html}</li>")
            parts.append("</ul>")
        else:
            parts.append("<p style='color:var(--text-muted)'>No cards.</p>")
        parts.append("</div>")
    parts.append("</div>")  # grid

    # Last sprint's action items + their recorded progress.
    if report.carried_action_items:
        parts.append("<h2>Last sprint&rsquo;s action items &mdash; progress</h2>")
        parts.append("<ul style='margin:0;padding-left:1.1rem'>")
        for c in report.carried_action_items:
            status = CARRIED_STATUS_LABELS.get(c.status or "pending", c.status or "Pending")
            parts.append(f"<li><strong style='color:var(--text-muted)'>[{_e(status)}]</strong> {_e(c.text)}</li>")
        parts.append("</ul>")

    parts.append("</div>")  # container
    body = "".join(parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_e(_title(report))} — {_e(report.date)}</title>
  <style>{_CSS}</style>
</head>
<body>
{body}
<footer class="site-footer">
  Generated by yeaboi.ai &bull; {_e(datetime.now().strftime("%Y-%m-%d"))}
</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_retro(report: RetroReport, *, project_name: str = "") -> dict[str, Path]:
    """Write the retro as Markdown + HTML under the retro export dir.

    Returns ``{"markdown": Path, "html": Path}``. One file per day (dated
    filename) — a re-run the same day overwrites so the latest wins.
    """
    from yeaboi.paths import get_retro_export_dir

    key = _slug(project_name or report.project_name or report.session_id)
    out_dir = get_retro_export_dir(key)
    stem = f"retro-{report.date or 'latest'}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_retro_markdown(report), encoding="utf-8")
    html_path.write_text(build_retro_html(report), encoding="utf-8")
    logger.info("Retro exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
