"""Export a DeliveryReport to Markdown, self-contained HTML, and a slide deck.

Mirrors the standup / retro exporters (standup/export.py, retro/export.py):
readable artifacts written under ``~/.scrum-agent/exports/reporting/<project>/`` so a
delivery report persists as a shareable document, not just in the logs. Three files
per run: a Markdown summary, a self-contained HTML report (reusing the plan
stylesheet ``html_exporter._CSS``), and a self-contained HTML *slide deck*
(reporting/presentation.py) for presenting to the business.

Every ticket ``title`` / ``assignee`` is external data (it came from the tracker),
so the HTML escapes every field with ``html.escape`` — the same defense the other
exporters use. The TUI **Export** button re-writes on demand.

# See README: "Export Formats" — Markdown, HTML
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from html import escape as _e
from pathlib import Path

from scrum_agent.agent.state import DeliveryReport

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "report"


def _emoji(report: DeliveryReport, slot: str) -> str:
    """Return the emoji chosen for ``slot`` (with trailing space), or ''."""
    for s, e in report.emoji_theme:
        if s == slot and e:
            return f"{e} "
    return ""


def _title(report: DeliveryReport) -> str:
    proj = f" — {report.project_name}" if report.project_name else ""
    return f"Delivery Report{proj}"


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_report_markdown(report: DeliveryReport) -> str:
    """Return the delivery report as a Markdown document."""
    lines: list[str] = [
        f"# {_emoji(report, 'headline')}{_title(report)}",
        "",
        f"**Period:** {report.period_label}  ",
        f"**Dates:** {report.period_start} to {report.period_end}",
        "",
    ]
    if report.sprint_names:
        lines += [f"**Sprint(s):** {', '.join(report.sprint_names)}", ""]
    if report.headline:
        lines += [f"> {report.headline}", ""]
    if report.metrics:
        lines += [f"## {_emoji(report, 'metrics')}By the numbers", ""]
        lines += [f"- **{label}:** {value}" for label, value in report.metrics]
        lines += [""]
    if report.executive_summary:
        lines += [f"## {_emoji(report, 'summary')}Executive summary", "", report.executive_summary, ""]
    for ttitle, outcomes in report.themes:
        lines += [f"## {_emoji(report, 'themes')}{ttitle}", ""]
        lines += [f"- {o}" for o in outcomes]
        lines += [""]
    if report.highlights:
        lines += [f"## {_emoji(report, 'highlights')}Highlights", ""]
        lines += [f"- {h}" for h in report.highlights]
        lines += [""]
    if report.delivered_items:
        lines += ["## Delivered items", ""]
        for it in report.delivered_items:
            who = f" — _{it.assignee}_" if it.assignee else ""
            lines.append(f"- `{it.key}` {it.title} ({it.status}){who}")
        lines += [""]
    if report.warnings:
        lines += ["## ⚠ Notices", ""]
        lines += [f"- {w}" for w in report.warnings]
        lines += [""]
    lines += [f"_Generated by yeaboi.ai · {datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def _html_list(items: tuple[str, ...]) -> str:
    return "<ul>" + "".join(f"<li>{_e(it)}</li>" for it in items) + "</ul>"


def build_report_html(report: DeliveryReport) -> str:
    """Return the delivery report as a self-contained HTML document (reuses plan CSS)."""
    from scrum_agent.html_exporter import _CSS

    parts: list[str] = [
        '<div class="container">',
        f"<h1>{_e(_emoji(report, 'headline'))}{_e(_title(report))}</h1>",
        (
            "<p style='color:var(--text-muted)'>"
            f"{_e(report.period_label)} &bull; {_e(report.period_start)} to {_e(report.period_end)}</p>"
        ),
    ]
    if report.headline:
        parts.append(f"<blockquote><strong>{_e(report.headline)}</strong></blockquote>")
    if report.metrics:
        cards = "".join(
            "<div style='border:1px solid var(--border,#30363d);border-radius:8px;padding:.6rem 1rem;"
            "min-width:120px'>"
            f"<div style='font-size:1.6rem;font-weight:700'>{_e(value)}</div>"
            f"<div style='color:var(--text-muted);font-size:.85rem'>{_e(label)}</div></div>"
            for label, value in report.metrics
        )
        parts.append(f"<h2>{_e(_emoji(report, 'metrics'))}By the numbers</h2>")
        parts.append(f"<div style='display:flex;flex-wrap:wrap;gap:.8rem'>{cards}</div>")
    if report.executive_summary:
        body = _e(report.executive_summary).replace("\n", "<br>")
        parts.append(f"<h2>{_e(_emoji(report, 'summary'))}Executive summary</h2><p>{body}</p>")
    for ttitle, outcomes in report.themes:
        parts.append(f"<h2>{_e(_emoji(report, 'themes'))}{_e(ttitle)}</h2>{_html_list(outcomes)}")
    if report.highlights:
        parts.append(f"<h2>{_e(_emoji(report, 'highlights'))}Highlights</h2>{_html_list(report.highlights)}")
    if report.delivered_items:
        rows = "".join(
            f"<tr><td><code>{_e(it.key)}</code></td><td>{_e(it.title)}</td>"
            f"<td>{_e(it.status)}</td><td>{_e(it.assignee)}</td></tr>"
            for it in report.delivered_items
        )
        parts.append(
            "<h2>Delivered items</h2>"
            "<table><thead><tr><th>Key</th><th>Title</th><th>Status</th><th>Delivered by</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )
    if report.warnings:
        parts.append(f"<h2>⚠ Notices</h2>{_html_list(report.warnings)}")
    parts.append("</div>")
    body = "".join(parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_e(_title(report))} — {_e(report.period_end)}</title>
  <style>{_CSS}</style>
</head>
<body>
{body}
<footer class="site-footer">
  Generated by yeaboi.ai &bull; {_e(datetime.now().strftime("%Y-%m-%d"))}
</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------


def export_report(report: DeliveryReport, *, project_name: str = "", theme: str = "midnight") -> dict[str, Path]:
    """Write the report as Markdown + HTML + a slide deck under the reporting export dir.

    Returns ``{"markdown": Path, "html": Path, "slides": Path}``. Filenames carry the
    period + end date — a re-run for the same period/day overwrites so the latest wins.
    """
    from scrum_agent.paths import get_reporting_export_dir
    from scrum_agent.reporting.presentation import build_presentation_html

    key = _slug(project_name or report.project_name or "report")
    out_dir = get_reporting_export_dir(key)
    period_slug = _slug(report.period_label) or "period"
    stem = f"report-{period_slug}-{report.period_end or 'latest'}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    slides_path = out_dir / f"{stem}-slides.html"
    md_path.write_text(build_report_markdown(report), encoding="utf-8")
    html_path.write_text(build_report_html(report), encoding="utf-8")
    slides_path.write_text(build_presentation_html(report, theme=theme), encoding="utf-8")
    logger.info("Reporting exported: %s , %s , %s", md_path, html_path, slides_path)
    return {"markdown": md_path, "html": html_path, "slides": slides_path}
