"""Build a self-contained HTML slide deck from a DeliveryReport.

This is the "presentation" output of Reporting mode: one offline .html file — inline
CSS + JS, no external dependencies — that opens in any browser and presents the
delivered work to the business. It follows the same embedded-asset pattern as
retro/page.py: big ``_CSS`` / ``_JS`` module strings with ``__PLACEHOLDER__`` markers
filled via ``str.replace`` + ``json.dumps``.

Design split (the "hybrid" the user chose): the *content* — slide wording, the
outcome themes, and the section emojis — is supplied by the LLM design pass in
engine.py (with a deterministic fallback). This file only *renders* it: layout,
theme palettes, keyboard navigation, progress. Ticket/outcome text is written to the
DOM via ``textContent`` (never innerHTML), so anything that came from a tracker is
inert — the same XSS defense the retro page uses.

This module is E501-exempt in pyproject.toml (embedded asset).

# See README: "Reporting Mode" — presentation output
# See README: "Retro Mode" — self-contained embedded HTML page pattern
"""

from __future__ import annotations

import json
from datetime import datetime

from scrum_agent.agent.state import DeliveryReport

# Theme names offered by the deck; the viewer cycles them with the "T" key.
THEMES = ("midnight", "aurora", "sunset", "mono")


def _json_for_script(value) -> str:
    """JSON-encode ``value`` safely for embedding inside an inline ``<script>``.

    ``json.dumps`` does not escape ``<`` / ``>`` / ``&``, so an untrusted ticket
    title containing ``</script>`` would otherwise break out of the script element
    and execute as markup. Escaping these to their ``\\uXXXX`` forms keeps the JSON
    valid while making a ``</script>`` breakout impossible — the standard mitigation
    for JSON-in-HTML. Ticket text is still rendered client-side via ``textContent``,
    so this is defense in depth.
    """
    return json.dumps(value, ensure_ascii=False).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def _emoji(report: DeliveryReport, slot: str, default: str = "") -> str:
    for s, e in report.emoji_theme:
        if s == slot and e:
            return e
    return default


def _build_slides(report: DeliveryReport) -> list[dict]:
    """Turn a DeliveryReport into an ordered list of slide dicts for the JS renderer.

    All text stays as plain strings — the client renders it via textContent, so
    untrusted ticket titles cannot inject markup.
    """
    slides: list[dict] = []
    dates = f"{report.period_start} to {report.period_end}".strip(" to")
    subtitle = report.period_label + (f"  ·  {dates}" if dates else "")
    if report.sprint_names:
        subtitle += f"  ·  {', '.join(report.sprint_names)}"

    slides.append(
        {
            "type": "title",
            "emoji": _emoji(report, "headline", "🚀"),
            "title": report.project_name or "Delivery Report",
            "subtitle": subtitle,
            "headline": report.headline,
        }
    )
    if report.executive_summary:
        slides.append(
            {
                "type": "summary",
                "emoji": _emoji(report, "summary", "📋"),
                "title": "Executive summary",
                "body": report.executive_summary,
            }
        )
    if report.metrics:
        slides.append(
            {
                "type": "metrics",
                "emoji": _emoji(report, "metrics", "📊"),
                "title": "By the numbers",
                "metrics": [[label, value] for label, value in report.metrics],
            }
        )
    for ttitle, outcomes in report.themes:
        slides.append(
            {
                "type": "list",
                "emoji": _emoji(report, "themes", "🧩"),
                "title": ttitle,
                "items": list(outcomes),
            }
        )
    if report.highlights:
        slides.append(
            {
                "type": "list",
                "emoji": _emoji(report, "highlights", "⭐"),
                "title": "Highlights",
                "items": list(report.highlights),
            }
        )
    slides.append(
        {
            "type": "thanks",
            "emoji": _emoji(report, "thanks", "🙌"),
            "title": "Thank you",
            "subtitle": report.project_name or "",
        }
    )
    return slides


def build_presentation_html(report: DeliveryReport, *, theme: str = "midnight") -> str:
    """Return a self-contained HTML slide deck presenting the delivery report."""
    theme = theme if theme in THEMES else "midnight"
    slides = _build_slides(report)
    footer = f"Generated by Scrum AI Agent · {datetime.now().strftime('%Y-%m-%d')}"
    js = (
        _JS.replace("__SLIDES__", _json_for_script(slides))
        .replace("__THEME__", _json_for_script(theme))
        .replace("__THEMES__", _json_for_script(list(THEMES)))
    )
    title = report.project_name or "Delivery Report"
    # Title bar text is our own (project name); still escape the couple of dynamic bits.
    safe_title = title.replace("<", "&lt;").replace(">", "&gt;")
    return f"""<!DOCTYPE html>
<html lang="en" data-theme="{theme}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{safe_title} — Delivery Report</title>
<style>{_CSS}</style>
</head>
<body>
<div id="deck" aria-live="polite"></div>
<div id="chrome">
  <div id="progress"><div id="bar"></div></div>
  <div id="controls">
    <button id="prev" aria-label="Previous slide">‹</button>
    <span id="counter">1 / 1</span>
    <button id="next" aria-label="Next slide">›</button>
    <button id="themeBtn" title="Cycle theme (T)">◑</button>
  </div>
  <div id="hint">← / → or Space to navigate · T for theme · F fullscreen</div>
</div>
<footer id="footer">{footer}</footer>
<script>{js}</script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Embedded CSS — theme palettes + slide layout
# ---------------------------------------------------------------------------

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
:root, [data-theme="midnight"] { --bg1:#0d1117; --bg2:#161b2e; --fg:#e6edf3; --muted:#9aa4b2; --accent:#8c78e6; --accent2:#b8a6ff; --card:rgba(255,255,255,.05); --border:rgba(255,255,255,.10); }
[data-theme="aurora"] { --bg1:#04121a; --bg2:#0a2a2a; --fg:#e8fff6; --muted:#8fc9be; --accent:#28c2a0; --accent2:#6ff0d0; --card:rgba(255,255,255,.06); --border:rgba(255,255,255,.12); }
[data-theme="sunset"] { --bg1:#1a0d16; --bg2:#3a1424; --fg:#fff1e8; --muted:#d9a08f; --accent:#f0784e; --accent2:#ffb27a; --card:rgba(255,255,255,.06); --border:rgba(255,255,255,.12); }
[data-theme="mono"] { --bg1:#0b0b0c; --bg2:#1c1c1f; --fg:#f4f4f5; --muted:#a1a1aa; --accent:#d4d4d8; --accent2:#ffffff; --card:rgba(255,255,255,.05); --border:rgba(255,255,255,.10); }
html, body { height: 100%; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: radial-gradient(circle at 30% 20%, var(--bg2), var(--bg1) 70%); color: var(--fg); overflow: hidden; }
#deck { height: 100vh; display: flex; align-items: center; justify-content: center; padding: 6vh 8vw 12vh; }
.slide { width: 100%; max-width: 980px; animation: fade .45s ease; }
@keyframes fade { from { opacity: 0; transform: translateY(14px); } to { opacity: 1; transform: none; } }
.emoji { font-size: clamp(3rem, 9vw, 6rem); line-height: 1; margin-bottom: 1.2rem; }
h1 { font-size: clamp(2rem, 6vw, 4rem); font-weight: 800; letter-spacing: -.02em; line-height: 1.05; }
h2 { font-size: clamp(1.6rem, 4.5vw, 3rem); font-weight: 800; letter-spacing: -.02em; margin-bottom: 1.4rem; background: linear-gradient(90deg, var(--accent2), var(--accent)); -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent; }
.sub { color: var(--muted); font-size: clamp(1rem, 2.4vw, 1.4rem); margin-top: 1.2rem; }
.headline { font-size: clamp(1.2rem, 3vw, 1.8rem); margin-top: 1.8rem; font-weight: 600; color: var(--accent2); }
.body { font-size: clamp(1.1rem, 2.6vw, 1.6rem); line-height: 1.6; color: var(--fg); }
ul.items { list-style: none; display: flex; flex-direction: column; gap: .9rem; }
ul.items li { font-size: clamp(1.05rem, 2.5vw, 1.5rem); line-height: 1.4; padding-left: 2.2rem; position: relative; }
ul.items li::before { content: "▸"; color: var(--accent); position: absolute; left: 0; top: 0; }
.metrics { display: flex; flex-wrap: wrap; gap: 1.2rem; }
.metric { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 1.6rem 2rem; min-width: 160px; }
.metric .val { font-size: clamp(2.4rem, 6vw, 4rem); font-weight: 800; color: var(--accent2); }
.metric .lab { color: var(--muted); margin-top: .3rem; font-size: 1rem; }
.center { text-align: center; }
#chrome { position: fixed; left: 0; right: 0; bottom: 0; padding: .8rem 1.2rem 1rem; }
#progress { height: 4px; background: var(--border); border-radius: 4px; overflow: hidden; margin-bottom: .7rem; }
#bar { height: 100%; width: 0; background: linear-gradient(90deg, var(--accent), var(--accent2)); transition: width .35s ease; }
#controls { display: flex; align-items: center; justify-content: center; gap: 1rem; }
#controls button { background: var(--card); border: 1px solid var(--border); color: var(--fg); width: 40px; height: 40px; border-radius: 50%; font-size: 1.2rem; cursor: pointer; transition: background .2s, transform .1s; }
#controls button:hover { background: var(--border); }
#controls button:active { transform: scale(.92); }
#counter { color: var(--muted); font-variant-numeric: tabular-nums; min-width: 64px; text-align: center; }
#hint { text-align: center; color: var(--muted); font-size: .8rem; margin-top: .6rem; opacity: .7; }
#footer { position: fixed; top: 1rem; right: 1.2rem; color: var(--muted); font-size: .75rem; opacity: .6; }
@media (max-width: 640px) { #hint { display: none; } }
"""

# ---------------------------------------------------------------------------
# Embedded JS — renderer + navigation (SLIDES / THEME injected by str.replace)
# ---------------------------------------------------------------------------

_JS = """
const SLIDES = __SLIDES__;
const THEMES = __THEMES__;
let theme = __THEME__;
let i = 0;

const deck = document.getElementById('deck');
const bar = document.getElementById('bar');
const counter = document.getElementById('counter');

function el(tag, cls, text) {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text != null) n.textContent = text;   // textContent → untrusted text is inert
  return n;
}

function render() {
  if (i < 0) i = 0;
  if (i > SLIDES.length - 1) i = SLIDES.length - 1;
  const s = SLIDES[i] || {};
  const slide = el('div', 'slide' + ((s.type === 'title' || s.type === 'thanks') ? ' center' : ''));
  if (s.emoji) slide.appendChild(el('div', 'emoji', s.emoji));

  if (s.type === 'title') {
    slide.appendChild(el('h1', null, s.title || 'Delivery Report'));
    if (s.subtitle) slide.appendChild(el('div', 'sub', s.subtitle));
    if (s.headline) slide.appendChild(el('div', 'headline', s.headline));
  } else if (s.type === 'thanks') {
    slide.appendChild(el('h1', null, s.title || 'Thank you'));
    if (s.subtitle) slide.appendChild(el('div', 'sub', s.subtitle));
  } else if (s.type === 'summary') {
    slide.appendChild(el('h2', null, s.title || ''));
    slide.appendChild(el('div', 'body', s.body || ''));
  } else if (s.type === 'metrics') {
    slide.appendChild(el('h2', null, s.title || ''));
    const wrap = el('div', 'metrics');
    (s.metrics || []).forEach(m => {
      const card = el('div', 'metric');
      card.appendChild(el('div', 'val', String(m[1])));
      card.appendChild(el('div', 'lab', String(m[0])));
      wrap.appendChild(card);
    });
    slide.appendChild(wrap);
  } else {  // list
    slide.appendChild(el('h2', null, s.title || ''));
    const ul = el('ul', 'items');
    (s.items || []).forEach(it => ul.appendChild(el('li', null, it)));
    slide.appendChild(ul);
  }

  deck.replaceChildren(slide);
  counter.textContent = (i + 1) + ' / ' + SLIDES.length;
  bar.style.width = (SLIDES.length > 1 ? (i / (SLIDES.length - 1)) * 100 : 100) + '%';
}

function go(n) { i = Math.max(0, Math.min(SLIDES.length - 1, i + n)); render(); }
function cycleTheme() {
  const idx = (THEMES.indexOf(theme) + 1) % THEMES.length;
  theme = THEMES[idx];
  document.documentElement.setAttribute('data-theme', theme);
}

document.getElementById('prev').onclick = () => go(-1);
document.getElementById('next').onclick = () => go(1);
document.getElementById('themeBtn').onclick = cycleTheme;

document.addEventListener('keydown', e => {
  if (e.key === 'ArrowRight' || e.key === ' ' || e.key === 'PageDown') { e.preventDefault(); go(1); }
  else if (e.key === 'ArrowLeft' || e.key === 'PageUp') { e.preventDefault(); go(-1); }
  else if (e.key === 'Home') { i = 0; render(); }
  else if (e.key === 'End') { i = SLIDES.length - 1; render(); }
  else if (e.key === 't' || e.key === 'T') { cycleTheme(); }
  else if (e.key === 'f' || e.key === 'F') {
    if (document.fullscreenElement) document.exitFullscreen(); else document.documentElement.requestFullscreen();
  }
});

render();
"""
