"""Markdown export for agentwatch artifacts.

Markdown only, deliberately: every other mode's HTML export rides a dedicated
React export component in the committed web bundles, and agentwatch does not
have one yet — shipping HTML through another mode's component would wear the
wrong branding and payload shape. The HTML surface is a tracked follow-up for
the web-ux workstream; the export dict simply has no "html" key until then
(same convention as the missing-pptx path in reporting/export.py).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from yeaboi.agent.state import AgentAdvisorReport, AgentSecurityReport, AgentUsageReport

logger = logging.getLogger(__name__)


def _md_footer() -> list[str]:
    return ["", "---", f"*Generated by yeaboi.ai on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*", ""]


def build_usage_markdown(report: AgentUsageReport) -> str:
    """The agent usage report as a shareable Markdown document."""
    from yeaboi.agentwatch.billing import label_for

    lines: list[str] = [
        f"# Agent Usage — {report.period_start} → {report.period_end}",
        "",
        f"**≈ ${report.total_cost_usd:,.2f}** ({label_for(report.billing_kind)}) across "
        f"{report.session_count} session(s) — "
        f"{report.total_input_tokens:,} input / {report.total_output_tokens:,} output tokens, "
        f"cache {report.total_cache_read_tokens:,} read / {report.total_cache_write_tokens:,} written"
        + (f"; {report.cache_cost_share:.0%} of the estimate is cache traffic." if report.cache_cost_share else "."),
        "",
        f"*Costs are local estimates at public rates (as of {report.pricing_as_of}) — not a provider bill.*",
    ]
    if report.unknown_model_cost_share > 0:
        lines.append(
            f"*⚠ {report.unknown_model_cost_share:.0%} of the total is priced at a fallback tier "
            "(unknown model rates).*"
        )

    if report.by_model:
        lines += [
            "",
            "## By model",
            "",
            "| model | cost | input | output | cache r/w | calls |",
            "|---|---|---|---|---|---|",
        ]
        for r in report.by_model:
            marker = "" if r.known_pricing else " \\*"
            lines.append(
                f"| {r.model}{marker} | ${r.cost_usd:,.2f} | {r.input_tokens:,} | {r.output_tokens:,} "
                f"| {r.cache_read_tokens:,}/{r.cache_write_tokens:,} | {r.calls} |"
            )

    for title, rows in (("By project", report.by_project), ("By source", report.by_source)):
        if not rows:
            continue
        lines += ["", f"## {title}", "", "| | cost | sessions | input | output |", "|---|---|---|---|---|"]
        for r in rows:
            lines.append(f"| {r.key} | ${r.cost_usd:,.2f} | {r.sessions} | {r.input_tokens:,} | {r.output_tokens:,} |")

    if report.daily_trend:
        lines += ["", "## Daily trend", "", "| date | cost | sessions |", "|---|---|---|"]
        for point in report.daily_trend:
            lines.append(f"| {point.date} | ${point.cost_usd:,.2f} | {point.sessions} |")

    for title, items in (("Insights", report.insights), ("Recommendations", report.recommendations)):
        if items:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in items]

    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]

    lines += _md_footer()
    return "\n".join(lines)


_VERDICT_HEADINGS = (
    ("needs-decision", "Needs a decision"),
    ("unsure", "Worth a look"),
    ("test-data", "Looks like test data"),
    ("handled", "Handled"),
    ("info", "Informational"),
)


def build_security_markdown(report: AgentSecurityReport) -> str:
    """The agent security report as a shareable Markdown document: issues by verdict."""
    lines: list[str] = [
        f"# Agent Security — {report.scan_date}",
        "",
        f"**{report.verdict_line or report.posture}**",
        "",
        f"Posture: {report.posture} — {report.sessions_scanned} session(s) scanned, "
        f"{len(report.mcp_servers)} MCP server(s)"
        + (f", {report.dismissed_count} handled" if report.dismissed_count else "")
        + ".",
        "",
        "*Deterministic pattern scan — an indicator, not a security audit. Findings reference "
        "file and line; the matched text is never stored.*",
    ]
    if report.posture_reason:
        lines.append(f"*{report.posture_reason}*")
    if report.new_findings or report.resolved_findings:
        lines += [
            "",
            f"**+{len(report.new_findings)} new / −{len(report.resolved_findings)} resolved** since the last scan.",
        ]
    by_key = {f.key: f for f in report.findings}
    for verdict, heading in _VERDICT_HEADINGS:
        issues = [i for i in report.issues if i.verdict == verdict]
        if not issues:
            if verdict == "info" and report.hidden_info_count:
                lines += [
                    "",
                    f"## {heading} ({report.hidden_info_count})",
                    "",
                    "_Counted, not listed — run with `--show-info`._",
                ]
            continue
        lines += ["", f"## {heading} ({len(issues)})"]
        for issue in issues:
            meta = f"{issue.severity} · {issue.signals} signal(s) · {issue.sessions} session(s) · {issue.files} file(s)"
            if issue.last_seen:
                meta += f" · last {issue.last_seen}"
            lines += ["", f"### {issue.title}", "", meta]
            if issue.why:
                lines += ["", issue.why]
            if issue.fixes:
                lines += ["", "Fixes:"] + [
                    f"- **{fix.label}** — {fix.detail}" for fix in issue.fixes if fix.kind != "dismiss"
                ]
            rows = [by_key[k] for k in issue.finding_keys if k in by_key]
            if rows:
                lines += ["", "| where | line | × | context | verdict |", "|---|---|---|---|---|"]
                for f in rows:
                    where = f.project_label or f.location
                    times = str(f.occurrences) if f.occurrences > 1 else ""
                    lines.append(f"| {where} | {f.line_no or ''} | {times} | {f.context or '—'} | {f.verdict_reason} |")
    if report.mcp_servers:
        lines += ["", "## MCP servers", "", "| name | scope | transport | flags |", "|---|---|---|---|"]
        for record in report.mcp_servers:
            lines.append(f"| {record.name} | {record.scope} | {record.transport} | {', '.join(record.flags) or '—'} |")
    if report.summary and report.summary != report.verdict_line:
        lines += ["", "## Full write-up", "", report.summary]
    if report.recommendations:
        lines += ["", "## Recommendations", ""] + [f"- {item}" for item in report.recommendations]
    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]
    lines += _md_footer()
    return "\n".join(lines)


def build_advisor_markdown(report: AgentAdvisorReport) -> str:
    """The agent advisor report as a shareable Markdown document."""
    lines: list[str] = [
        f"# Agent Advisor — {report.period_start} → {report.period_end}",
        "",
        f"**~${report.recoverable_usd:,.2f} recoverable** of ${report.total_cost_usd:,.2f} estimated spend"
        + (f" ({report.recoverable_share:.0%})" if report.total_cost_usd > 0 else "")
        + f" — {report.files_audited} transcript(s) audited, "
        f"{report.read_calls} Read call(s) totalling {report.read_bytes:,} bytes.",
        "",
        f"*Estimates: tokens ≈ bytes/4, priced at ~${report.effective_input_rate_per_mtok:,.2f}/Mtok input "
        f"(rates as of {report.pricing_as_of}). Computed locally from session logs — a floor, not an invoice.*",
    ]
    if report.unknown_rate_share > 0:
        lines.append(
            f"*⚠ {report.unknown_rate_share:.0%} of input tokens priced at a fallback tier (unknown model rates).*"
        )

    items = [i for i in report.line_items if i.content_bytes]
    if items:
        lines += [
            "",
            "## Waste by mechanism",
            "",
            "| mechanism | calls | size | est. cost | of Read bytes | note |",
            "|---|---|---|---|---|---|",
        ]
        for i in items:
            marker = "" if i.recoverable else " \\*"
            lines.append(
                f"| {i.label}{marker} | {i.calls or '—'} | {i.est_tokens:,} tok | ${i.est_usd:,.2f} "
                f"| {i.share_of_read_bytes:.0%} | {i.note} |"
            )
        if any(not i.recoverable for i in items):
            lines.append("")
            lines.append("*\\* sized as context, not counted in the recoverable total.*")

    lines += [
        "",
        "## Cache health",
        "",
        f"- Alignment score: **{report.alignment_score}/100**",
        f"- A Read stays in context for a median of {report.residency_median} assistant turn(s) "
        f"(p90 {report.residency_p90}) — every retained turn re-bills it as cache reads.",
        f"- {report.gaps_over_5m} inter-message gap(s) over 5 minutes ({report.gaps_over_1h} over 1h) "
        f"across {report.sessions_with_gap} session(s) — likely cache-death windows.",
    ]
    if report.volatile_signals:
        lines += ["", "## Volatile content in prompt-prefix files", "", "| file | findings | kinds |", "|---|---|---|"]
        for s in report.volatile_signals:
            kinds = ", ".join(f"{label}×{count}" for label, count in s.counts)
            lines.append(f"| {s.location} | {s.total} | {kinds} |")

    for title, prose in (("Insights", report.insights), ("Recommendations", report.recommendations)):
        if prose:
            lines += ["", f"## {title}", ""] + [f"- {item}" for item in prose]

    if report.warnings:
        lines += ["", "## Warnings", ""] + [f"- ⚠ {w}" for w in report.warnings]

    lines += _md_footer()
    return "\n".join(lines)


_BUILDERS = {
    "usage": build_usage_markdown,
    "security": build_security_markdown,
    "advisor": build_advisor_markdown,
}


def build_markdown(artifact, *, kind: str) -> str:
    """The Markdown one kind's artifact renders as — what Export writes, Copy copies."""
    return _BUILDERS[kind](artifact)


def export_artifact(artifact, *, kind: str) -> dict[str, Path]:
    """Write ``artifact`` under ~/.yeaboi/exports/agentwatch/<kind>/; return paths.

    One dated file per kind — a same-day re-run overwrites, which is the
    blueprint's convention (the newest run is the truth for that day).
    """
    from yeaboi.paths import get_agentwatch_export_dir

    builder = _BUILDERS[kind]
    out_dir = get_agentwatch_export_dir(kind)
    stem = f"{kind}-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    md_path = out_dir / f"{stem}.md"
    md_path.write_text(builder(artifact), encoding="utf-8")
    logger.info("agentwatch export: wrote %s", md_path)
    return {"markdown": md_path}
