"""Publish generated Markdown exports to Notion / Confluence.

# See docs: "Tools" — this module deliberately bypasses the @tool wrappers in
tools/notion.py and tools/confluence.py. Those wrappers are for the LLM agent:
they return user-facing strings (success is indistinguishable from failure
programmatically), accept only plain text bodies, and can't batch. The TUI
Export buttons need structured success/failure and rich formatting, so this
layer uses the same client factories directly with markdown_convert output.

Every function here is best-effort and NEVER raises — failures become a
``PublishResult(ok=False, message=...)`` the TUI shows as a status line.

Destinations: an explicitly configured exports page (Setup → Docs) is used
directly; otherwise docs are grouped under an auto-created **🤙 yeaboi**
container page (under the Notion root page / at the Confluence space root) so
everything yeaboi publishes stays together.
"""

from __future__ import annotations

import logging
import mimetypes
import os
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from yeaboi.config import (
    get_confluence_base_url,
    get_confluence_export_parent_page_id,
    get_confluence_space_key,
    get_notion_root_page_id,
)
from yeaboi.markdown_convert import (
    extract_image_paths,
    markdown_to_confluence_storage,
    markdown_to_notion_blocks,
)

logger = logging.getLogger(__name__)

# Notion rejects pages.create / blocks.children.append calls with more than
# 100 children — long documents (plans, team profiles) are appended in chunks.
_NOTION_BLOCK_BATCH = 100

# Images above this size are skipped rather than uploaded/copied — matches the
# paste-time cap in ui/shared/_attachments.py with headroom for charts.
_MAX_IMAGE_BYTES = 5 * 1024 * 1024

# yeaboi branding on published pages: page icon (Notion), page label
# (Confluence), and a linked footer appended when a builder didn't already
# brand the document.
_BRAND_EMOJI = "🤙"
_BRAND_LABEL = "yeaboi"
_BRAND_FOOTER = "---\n\n🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)_"

# When no explicit exports page is configured, docs are grouped under an
# auto-created container page instead of scattering at the root. Notion pages
# get the emoji as a page icon; Confluence has no icons, so it's in the title.
_BRAND_PARENT_NOTION = "yeaboi"
_BRAND_PARENT_CONFLUENCE = "🤙 yeaboi"
_BRAND_PARENT_INTRO = "Documents published by yeaboi."

# One resolve per session: ("notion", root_id) / ("confluence", space) → page
# id. Popped on publish failure so a deleted container is re-resolved.
_brand_parent_cache: dict[tuple[str, str], str] = {}

DEST_NOTION = "notion"
DEST_CONFLUENCE = "confluence"

# Shown when the integration works but publishing is impossible: Notion can't
# create top-level pages (needs a root or exports page), and a Confluence page
# must live in a space. Both are collected in Setup → Docs.
NOTION_PATH_HINT = "Add a Notion page in Setup → Docs — Notion needs a page to publish under"
CONFLUENCE_PATH_HINT = "Add a Confluence space key in Setup → Docs"


@dataclass(frozen=True)
class PublishResult:
    """Outcome of a publish attempt — message is ready for the TUI status line."""

    ok: bool
    message: str
    url: str = ""


def _publishable_images(markdown: str) -> list[Path]:
    """Existing, size-guarded image files referenced by ``![alt](path)`` lines."""
    out: list[Path] = []
    for raw in extract_image_paths(markdown):
        p = Path(raw)
        if not p.is_file():
            logger.warning("Export image missing on disk, skipping: %s", raw)
            continue
        if p.stat().st_size > _MAX_IMAGE_BYTES:
            logger.warning("Export image over %d bytes, skipping: %s", _MAX_IMAGE_BYTES, raw)
            continue
        out.append(p)
    return out


def _unique_names(paths: list[Path]) -> dict[str, str]:
    """Map each path to a collision-free attachment filename."""
    names: dict[str, str] = {}
    used: set[str] = set()
    for p in paths:
        name, i = p.name, 1
        while name in used:
            name = f"{p.stem}-{i}{p.suffix}"
            i += 1
        used.add(name)
        names[str(p)] = name
    return names


def _upload_notion_images(client, markdown: str) -> dict[str, str]:
    """Upload referenced images via the Notion File Upload API → {path: upload id}.

    Best-effort per image — a failed upload logs a warning and the image
    degrades to a placeholder paragraph in the converted blocks.
    """
    ids: dict[str, str] = {}
    for p in _publishable_images(markdown):
        mime = mimetypes.guess_type(p.name)[0] or "application/octet-stream"
        try:
            upload = client.file_uploads.create(mode="single_part", filename=p.name, content_type=mime)
            with p.open("rb") as fh:
                client.file_uploads.send(file_upload_id=upload["id"], file=(p.name, fh, mime))
            ids[str(p)] = upload["id"]
            logger.info("Notion image uploaded: %s (%s)", p.name, upload["id"])
        except Exception as e:  # noqa: BLE001 — image upload is best-effort
            logger.warning("Notion image upload failed for %s: %s", p, e)
    return ids


def localize_images(markdown: str, dest_dir: Path) -> str:
    """Copy referenced images into ``dest_dir/images/`` and relink relatively.

    Used by the .md file exports so the export folder is self-contained (the
    original screenshots live in ~/.yeaboi/attachments and may be pruned).
    Best-effort: a missing/failed image keeps its original absolute link.
    """
    paths = _publishable_images(markdown)
    if not paths:
        return markdown
    names = _unique_names(paths)
    img_dir = dest_dir / "images"
    for p in paths:
        name = names[str(p)]
        try:
            if p.is_relative_to(dest_dir):
                # Already inside the export folder (e.g. a freshly rendered
                # chart) — just relink relatively, no copy needed.
                markdown = markdown.replace(f"]({p})", f"]({p.relative_to(dest_dir)})")
                continue
            img_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, img_dir / name)
            markdown = markdown.replace(f"]({p})", f"](images/{name})")
        except Exception as e:  # noqa: BLE001 — localizing is best-effort
            logger.warning("Could not localize export image %s: %s", p, e)
    return markdown


def _ensure_notion_brand_parent(client, root_id: str) -> str | None:
    """Find-or-create the "yeaboi" container page under *root_id* → its id.

    Grouping is best-effort: any lookup/create failure logs a warning and
    returns None, and the caller publishes directly under the root instead.
    """
    key = ("notion", root_id)
    if key in _brand_parent_cache:
        return _brand_parent_cache[key]
    try:
        # Scan the root page's children for an existing container page.
        cursor: str | None = None
        while True:
            kwargs = {"start_cursor": cursor} if cursor else {}
            resp = client.blocks.children.list(block_id=root_id, **kwargs)
            for block in resp.get("results", []):
                if block.get("type") == "child_page" and block["child_page"].get("title") == _BRAND_PARENT_NOTION:
                    _brand_parent_cache[key] = block["id"]
                    logger.info("Notion yeaboi container reused: %s", block["id"])
                    return block["id"]
            if not resp.get("has_more"):
                break
            cursor = resp.get("next_cursor")
        page = client.pages.create(
            parent={"page_id": root_id},
            properties={"title": [{"type": "text", "text": {"content": _BRAND_PARENT_NOTION}}]},
            icon={"type": "emoji", "emoji": _BRAND_EMOJI},
            children=[
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {"rich_text": [{"type": "text", "text": {"content": _BRAND_PARENT_INTRO}}]},
                }
            ],
        )
        _brand_parent_cache[key] = page["id"]
        logger.info("Notion yeaboi container created: %s", page["id"])
        return page["id"]
    except Exception as e:  # noqa: BLE001 — grouping is best-effort, never block the publish
        logger.warning("Notion yeaboi container unavailable, publishing under root: %s", e)
        return None


def _ensure_confluence_brand_parent(conf, space: str) -> str | None:
    """Find-or-create the "🤙 yeaboi" container page in *space* → its id.

    Best-effort like the Notion counterpart — None means publish at the space
    root as before. Confluence titles are unique per space, so a title lookup
    is a reliable existence check.
    """
    key = ("confluence", space)
    if key in _brand_parent_cache:
        return _brand_parent_cache[key]
    try:
        page = conf.get_page_by_title(space, _BRAND_PARENT_CONFLUENCE)
        if not page:
            page = conf.create_page(
                space=space,
                title=_BRAND_PARENT_CONFLUENCE,
                body=f"<p>{_BRAND_PARENT_INTRO}</p>",
            )
            logger.info("Confluence yeaboi container created: %s", page.get("id", ""))
        else:
            logger.info("Confluence yeaboi container reused: %s", page.get("id", ""))
        page_id = page.get("id", "")
        if page_id:
            _brand_parent_cache[key] = page_id
        return page_id or None
    except Exception as e:  # noqa: BLE001 — grouping is best-effort, never block the publish
        logger.warning("Confluence yeaboi container unavailable, publishing at space root: %s", e)
        return None


def publish_to_notion(title: str, markdown: str) -> PublishResult:
    """Create a Notion page under the exports page, else the 🤙 yeaboi container.

    An explicitly configured NOTION_EXPORT_PARENT_PAGE_ID is used directly.
    Otherwise docs are grouped under a "yeaboi" container page (🤙 icon)
    found-or-created under NOTION_ROOT_PAGE_ID.
    """
    logger.info("Notion export requested: %r", title)
    explicit = os.getenv("NOTION_EXPORT_PARENT_PAGE_ID") or ""
    root = get_notion_root_page_id() or ""
    if not explicit and not root:
        logger.warning("Notion export blocked: no exports page or root page configured")
        return PublishResult(ok=False, message=NOTION_PATH_HINT)

    # Lazy import — the SDK and its config guards live with the tool module.
    from yeaboi.tools.notion import _make_notion_client

    client = _make_notion_client()
    if client is None:
        logger.warning("Notion export blocked: NOTION_TOKEN not configured")
        return PublishResult(ok=False, message="Notion is not configured — set NOTION_TOKEN in Settings")

    parent = explicit or _ensure_notion_brand_parent(client, root) or root

    # Upload screenshots/charts first so the blocks can reference them natively.
    image_ids = _upload_notion_images(client, markdown)
    blocks = markdown_to_notion_blocks(markdown, image_ids=image_ids)
    try:
        page = client.pages.create(
            parent={"page_id": parent},
            properties={"title": [{"type": "text", "text": {"content": title}}]},
            icon={"type": "emoji", "emoji": _BRAND_EMOJI},
            children=blocks[:_NOTION_BLOCK_BATCH],
        )
        page_id = page.get("id", "")
        # Append the rest in 100-block batches (Notion's per-call children limit).
        for i in range(_NOTION_BLOCK_BATCH, len(blocks), _NOTION_BLOCK_BATCH):
            client.blocks.children.append(page_id, children=blocks[i : i + _NOTION_BLOCK_BATCH])
        url = page.get("url", "")
        logger.info("Notion export succeeded: %r (%d blocks) -> %s", title, len(blocks), url)
        return PublishResult(ok=True, message=f"Exported to Notion: {title}", url=url)
    except Exception as e:  # noqa: BLE001 — publish is best-effort, never crash the TUI
        # The cached container may have been deleted — re-resolve next attempt.
        _brand_parent_cache.pop(("notion", root), None)
        try:
            from notion_client.errors import APIResponseError

            from yeaboi.tools.notion import _notion_error_msg

            if isinstance(e, APIResponseError):
                msg = _notion_error_msg(e)
            else:
                msg = f"Notion export failed: {e}"
        except Exception:
            msg = f"Notion export failed: {e}"
        logger.warning("Notion export failed for %r: %s", title, e)
        return PublishResult(ok=False, message=msg)


def publish_to_confluence(title: str, markdown: str) -> PublishResult:
    """Create a Confluence page in the configured space, grouped under 🤙 yeaboi.

    An explicitly configured CONFLUENCE_EXPORT_PARENT_PAGE_ID is used directly.
    Otherwise docs nest under a "🤙 yeaboi" container page found-or-created at
    the root of the space (falling back to the space root if that fails).
    """
    logger.info("Confluence export requested: %r", title)
    space = get_confluence_space_key()
    if not space:
        logger.warning("Confluence export blocked: CONFLUENCE_SPACE_KEY not set")
        return PublishResult(ok=False, message=CONFLUENCE_PATH_HINT)

    from yeaboi.tools.confluence import _make_confluence_client

    conf = _make_confluence_client()
    if conf is None:
        logger.warning("Confluence export blocked: credentials not configured")
        return PublishResult(
            ok=False, message="Confluence is not configured — set the Confluence credentials in Settings"
        )

    # Confluence rejects duplicate titles within a space, and re-exporting the
    # same report is the normal case — timestamp the title to keep it unique.
    stamped_title = f"{title} · {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    # Attachments can only be uploaded once the page exists, so the body is
    # created with <ri:attachment> macros first and the files attached after —
    # Confluence resolves the macros as soon as the named attachments arrive.
    images = _publishable_images(markdown)
    image_names = _unique_names(images)
    # Exports page from setup wins; else group under the 🤙 yeaboi container
    # (None → space root when the container can't be resolved either).
    parent_id = get_confluence_export_parent_page_id() or _ensure_confluence_brand_parent(conf, space)
    try:
        page = conf.create_page(
            space=space,
            title=stamped_title,
            body=markdown_to_confluence_storage(markdown, image_filenames=image_names),
            parent_id=parent_id,
        )
        page_id = page.get("id", "")
        for p in images:
            try:
                conf.attach_file(str(p), name=image_names[str(p)], page_id=page_id)
                logger.info("Confluence image attached: %s -> page %s", image_names[str(p)], page_id)
            except Exception as e:  # noqa: BLE001 — attachment is best-effort, page already exists
                logger.warning("Confluence image attach failed for %s: %s", p, e)
        try:
            # Real Confluence label so yeaboi pages are search/filterable.
            conf.set_page_label(page_id, _BRAND_LABEL)
            logger.info("Confluence label %r set on page %s", _BRAND_LABEL, page_id)
        except Exception as e:  # noqa: BLE001 — labelling is best-effort, page already exists
            logger.warning("Confluence label failed for page %s: %s", page_id, e)
        base_url = (get_confluence_base_url() or "").rstrip("/")
        web_ui = page.get("_links", {}).get("webui", f"/wiki/pages/{page_id}")
        url = f"{base_url}{web_ui}"
        logger.info("Confluence export succeeded: %r -> %s", stamped_title, url)
        return PublishResult(ok=True, message=f"Exported to Confluence: {stamped_title}", url=url)
    except Exception as e:  # noqa: BLE001 — publish is best-effort, never crash the TUI
        # The cached container may have been deleted — re-resolve next attempt.
        _brand_parent_cache.pop(("confluence", space), None)
        try:
            from requests.exceptions import HTTPError

            from yeaboi.tools.confluence import _confluence_error_msg

            if isinstance(e, HTTPError):
                msg = _confluence_error_msg(e)
            else:
                msg = f"Confluence export failed: {e}"
        except Exception:
            msg = f"Confluence export failed: {e}"
        logger.warning("Confluence export failed for %r: %s", title, e)
        return PublishResult(ok=False, message=msg)


def publish_markdown(destination: str, *, title: str, markdown: str) -> PublishResult:
    """Dispatch a markdown document to the chosen destination ("notion"/"confluence").

    Documents whose builder didn't already brand them get the yeaboi footer
    (divider + linked credit line) appended before conversion.
    """
    if "yeaboi.ai" not in markdown:
        markdown = f"{markdown.rstrip()}\n\n{_BRAND_FOOTER}\n"
    if destination == DEST_NOTION:
        return publish_to_notion(title, markdown)
    if destination == DEST_CONFLUENCE:
        return publish_to_confluence(title, markdown)
    logger.warning("Unknown export destination: %r", destination)
    return PublishResult(ok=False, message=f"Unknown export destination: {destination}")
