// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse activity state. `Unknown` is a real, common case — `sessions/*.json`
 * omits `status` entirely when it has never been set.
 */
export type ActivityStatus = "Busy" | "Idle" | "Dead" | "Unknown";
