// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressStatus } from "./ProgressStatus";

/**
 * Outcome of one agent×dimension run, for live progress.
 */
export type AgentProgress = { provider: string, category: string, status: ProgressStatus, };
