// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage of the latest turn against the model's context window.
 */
export type ContextUsage = { 
/**
 * Tokens occupying the context window right now (input + cache create + cache read).
 */
used: number, 
/**
 * The model's context window in tokens.
 */
window: number, 
/**
 * `used / window`, clamped to `[0, 1]`.
 */
pct: number, };
