// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * One review finding.
 */
export type Finding = { severity: Severity, 
/**
 * Which review dimension produced it (code / error-handling / …).
 */
category: string, file: string | null, line: number | null, title: string, body: string, 
/**
 * Which agent produced it (`claude` / `codex`).
 */
provider: string, };
