// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which host application launched the session, derived from `entrypoint`.
 */
export type HostApp = "Cli" | "VsCode" | { "Other": string };
