// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a PR should be merged.
 */
export type MergeMethod = "Merge" | "Squash" | "Rebase";
