// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A listening TCP port held by a session's process (or one of its children,
 * e.g. a dev server). Joined in from `lsof`.
 */
export type Port = { 
/**
 * The listening port number.
 */
number: number, 
/**
 * The pid holding the socket (may be a child of the session pid).
 */
pid: number, 
/**
 * Socket state as reported by lsof (e.g. `LISTEN`).
 */
state: string, };
