// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process metrics for a session's pid, joined in from the OS process table.
 */
export type ProcStats = { 
/**
 * Instantaneous CPU usage percentage (can exceed 100 across cores).
 */
cpu_pct: number, 
/**
 * Resident memory in bytes.
 */
mem_bytes: number, 
/**
 * Seconds since the process started.
 */
uptime_secs: number, 
/**
 * Parent pid, if known.
 */
ppid: number | null, };
