// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository the sessions roll up under. Worktrees of one repo collapse here.
 */
export type Project = { 
/**
 * Stable id (repo common-dir path, or cwd for non-git sessions).
 */
id: string, 
/**
 * Display name (repo folder name, or remote slug when available).
 */
name: string, 
/**
 * Filesystem root of the repo (or cwd).
 */
root: string, 
/**
 * `origin` remote URL, when the repo has one.
 */
remote: string | null, 
/**
 * Sessions belonging to this project.
 */
session_ids: Array<string>, busy_count: number, session_count: number, };
