// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pull request, flattened from `gh`'s JSON into the shape the app renders.
 */
export type PullRequest = { number: number, title: string, 
/**
 * `OPEN` | `CLOSED` | `MERGED`.
 */
state: string, 
/**
 * Source branch (`headRefName`).
 */
head: string, 
/**
 * Target branch (`baseRefName`).
 */
base: string, 
/**
 * Author login.
 */
author: string, url: string, is_draft: boolean, updated_at: string, };
