// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of rebasing a branch onto its base.
 */
export type RebaseOutcome = "Clean" | { "Conflicts": Array<string> };
