// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStatus } from "./ActivityStatus";
import type { ContextUsage } from "./ContextUsage";
import type { HostApp } from "./HostApp";
import type { Port } from "./Port";
import type { ProcStats } from "./ProcStats";
import type { Provider } from "./Provider";

/**
 * One AI coding session.
 */
export type Session = { 
/**
 * Provider session id (Claude `sessionId` / Codex `threads.id`).
 */
id: string, 
/**
 * OS process id, when known (Codex threads have none).
 */
pid: number | null, 
/**
 * Id of the [`Project`] this session rolls up under.
 */
project_id: string, provider: Provider, host_app: HostApp, 
/**
 * Working directory the session was launched in.
 */
cwd: string, 
/**
 * Human label if the session was named.
 */
name: string | null, 
/**
 * Model of the latest turn.
 */
model: string | null, status: ActivityStatus, 
/**
 * Git branch reported by the transcript / thread.
 */
branch: string | null, 
/**
 * Epoch ms the session started.
 */
started_at_ms: number, 
/**
 * Epoch ms of the last observed activity.
 */
updated_at_ms: number, 
/**
 * Context-window usage of the latest turn, if a usage line was seen.
 */
context: ContextUsage | null, 
/**
 * The most recent user prompt (truncated upstream).
 */
last_prompt: string | null, 
/**
 * Best-effort count of sub-agent (sidechain) activity in the transcript.
 */
sub_agent_count: number, 
/**
 * Best-effort: the session appears paused on a permission request (a
 * pending tool-use with no result while not actively working).
 */
awaiting_permission: boolean, 
/**
 * Process metrics joined in by pid, when the process is live.
 */
proc_stats: ProcStats | null, 
/**
 * Listening ports held by this session's process subtree.
 */
ports: Array<Port>, };
