// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal session shape for Phase 0. Phase 1 expands this into the full
 * `Session` (pid, cwd, model, context, sub-agents, ports, …).
 */
export type SessionStub = { id: string, project: string, status: string, };
