// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How serious a finding is.
 */
export type Severity = "Critical" | "Important" | "Suggestion" | "Info";
