// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { Session } from "./Session";
import type { Totals } from "./Totals";

/**
 * Immutable snapshot of everything the monitor knows at a point in time.
 */
export type Snapshot = { 
/**
 * Unix epoch milliseconds when this snapshot was built.
 */
generated_at_ms: number, projects: Array<Project>, sessions: Array<Session>, totals: Totals, 
/**
 * Non-fatal collector degradations to surface in the UI.
 */
warnings: Array<string>, };
