// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStub } from "./SessionStub";

/**
 * Immutable snapshot of everything the monitor knows at a point in time.
 */
export type Snapshot = { 
/**
 * Unix epoch milliseconds when this snapshot was built.
 */
generated_at_ms: number, 
/**
 * Sessions known at this tick (stub shape in Phase 0).
 */
sessions: Array<SessionStub>, 
/**
 * Non-fatal collector degradations to surface in the UI.
 */
warnings: Array<string>, };
