// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sub-agent (a `Task`/`Agent` tool call) launched during a session.
 */
export type SubAgent = { 
/**
 * The sub-agent type (e.g. `Explore`, `general-purpose`), or `""`.
 */
kind: string, 
/**
 * The task description it was given, or `""`.
 */
description: string, };
