// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rolled-up counts for the header line.
 */
export type Totals = { session_count: number, busy_count: number, project_count: number, };
