// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a session's transcript timeline (for replay).
 */
export type TranscriptEvent = { 
/**
 * `user` | `assistant` | `tool_use` | `tool_result` | `thinking` | …
 */
kind: string, 
/**
 * A short human summary of the entry.
 */
summary: string, };
