// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a session's transcript timeline (for replay).
 */
export type TranscriptEvent = { 
/**
 * One atomic entry: `user` | `assistant` | `thinking` | `tool_use` |
 * `tool_result` | `system` | … — the speaker/label is derived from this.
 */
kind: string, 
/**
 * A short human summary of the entry (≤160 chars) — for compact lists.
 */
summary: string, 
/**
 * The full entry text (generously bounded) — the readable reader content.
 */
text: string, 
/**
 * ISO8601 timestamp of the source line, or `""` if absent.
 */
at: string, };
