// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A worktree as the UI sees it.
 */
export type Worktree = { 
/**
 * Short name (the path leaf with the `<repo>-` prefix stripped).
 */
name: string, path: string, branch: string, 
/**
 * Deterministic dev-server port for this checkout.
 */
port: number, is_main: boolean, };
