"""OS-native scheduling for Daily Standup mode.

The whole point of this module is that a standup fires *even when yeaboi is
closed*. Rather than keep a daemon alive, we register a job with the operating
system's own scheduler — launchd on macOS, crontab on Linux — that runs
``yeaboi --standup-run --standup-session <id>`` at the configured time.

Everything is stdlib + subprocess (no APScheduler dependency). Platform is
dispatched on ``sys.platform``. Windows is unsupported (returns a clear message)
— on-demand runs from the TUI still work everywhere.

# See docs: "Daily Standup" — scheduling
"""

from __future__ import annotations

import logging
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

# launchd label / crontab marker are keyed by session so multiple projects can
# each have their own schedule without clobbering one another.
_LABEL_PREFIX = "com.yeaboi.standup"
_CRON_MARKER = "# yeaboi-standup"


def _executable_args(session_id: str) -> list[str]:
    """Return the argv the scheduler should invoke — the *interactive* standup run.

    Prefer an installed ``yeaboi`` on PATH (or the legacy ``scrum-agent`` alias);
    fall back to ``python -m yeaboi.cli`` so a dev/venv install still schedules
    correctly. The run is interactive: attached to a terminal it prompts for the
    user's update + confirm; with no TTY it falls back to headless generate+deliver.
    """
    exe = shutil.which("yeaboi") or shutil.which("scrum-agent")
    if exe:
        base = [exe]
    else:
        base = [sys.executable, "-m", "yeaboi.cli"]
    return [*base, "--standup-run", "--standup-interactive", "--standup-session", session_id]


def _parse_time(hhmm: str) -> tuple[int, int]:
    """Parse 'HH:MM' → (hour, minute). Raises ValueError on bad input."""
    parts = hhmm.strip().split(":")
    if len(parts) != 2:
        raise ValueError(f"Invalid time {hhmm!r} — expected HH:MM")
    hour, minute = int(parts[0]), int(parts[1])
    if not (0 <= hour < 24 and 0 <= minute < 60):
        raise ValueError(f"Time out of range: {hhmm!r}")
    return hour, minute


def run_time(standup_time: str, lead_minutes: int) -> tuple[int, int]:
    """Return the (hour, minute) the job should FIRE — ``lead_minutes`` before the standup.

    Wraps around midnight (mod 1440) if the lead pushes before 00:00, so an early
    standup with a large lead still yields a valid clock time.
    """
    hour, minute = _parse_time(standup_time)
    total = (hour * 60 + minute - int(lead_minutes)) % 1440
    return total // 60, total % 60


def run_time_str(standup_time: str, lead_minutes: int) -> str:
    """Return the fire time as 'HH:MM' (for display on the dashboard)."""
    h, m = run_time(standup_time, lead_minutes)
    return f"{h:02d}:{m:02d}"


def _weekday_list(weekdays: str) -> list[int]:
    """Expand a weekday spec ('1-5', '1,3,5') into a list of ints (Mon=1..Sun=7)."""
    result: list[int] = []
    for chunk in weekdays.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            lo, hi = chunk.split("-", 1)
            result.extend(range(int(lo), int(hi) + 1))
        else:
            result.append(int(chunk))
    return result or [1, 2, 3, 4, 5]


# ---------------------------------------------------------------------------
# macOS — launchd
# ---------------------------------------------------------------------------


def _launch_agents_dir() -> Path:
    return Path.home() / "Library" / "LaunchAgents"


def _plist_path(session_id: str) -> Path:
    safe = session_id.replace("/", "_")
    return _launch_agents_dir() / f"{_LABEL_PREFIX}.{safe}.plist"


def _launcher_dir() -> Path:
    return Path.home() / "Library" / "Application Support" / "yeaboi"


def _launcher_path(session_id: str) -> Path:
    safe = session_id.replace("/", "_")
    return _launcher_dir() / f"standup-{safe}.sh"


def _write_launcher_script(session_id: str) -> Path:
    """Write a tiny shell launcher that runs the interactive standup CLI.

    launchd opens Terminal against this script (via osascript). Using a script
    file — rather than embedding the command in the AppleScript string — avoids
    nested-quoting hell and keeps the plist simple.
    """
    import shlex

    path = _launcher_path(session_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = " ".join(shlex.quote(a) for a in _executable_args(session_id))
    path.write_text(f"#!/bin/sh\n# Auto-generated by yeaboi — Daily Standup schedule.\n{cmd}\n")
    path.chmod(0o755)
    return path


def _install_launchd(session_id: str, hour: int, minute: int, weekdays: list[int]) -> str:
    label = f"{_LABEL_PREFIX}.{session_id.replace('/', '_')}"
    # launchd Weekday: Sunday=0/7, Monday=1..Saturday=6. Our 1-7 (Mon-Sun) maps
    # directly except Sunday which we send as 0.
    intervals = [{"Hour": hour, "Minute": minute, "Weekday": (0 if wd == 7 else wd)} for wd in weekdays]

    # Open a Terminal window running the launcher so the run is INTERACTIVE (it can
    # prompt for the user's update). LaunchAgents run in the GUI session, so
    # AppleScript to Terminal works while the user is logged in.
    launcher = _write_launcher_script(session_id)
    osa = f'tell application "Terminal" to do script "{launcher}"'
    plist = {
        "Label": label,
        "ProgramArguments": ["/usr/bin/osascript", "-e", osa],
        "StartCalendarInterval": intervals,
        "RunAtLoad": False,
    }
    path = _plist_path(session_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as fh:
        plistlib.dump(plist, fh)
    logger.info("scheduler[launchd]: wrote %s (launcher %s)", path, launcher)
    # Reload: bootout any existing instance, then bootstrap the fresh plist.
    subprocess.run(["launchctl", "unload", str(path)], capture_output=True, timeout=10, check=False)
    proc = subprocess.run(["launchctl", "load", str(path)], capture_output=True, text=True, timeout=10, check=False)
    if proc.returncode != 0:
        logger.warning("scheduler[launchd]: load returned %d: %s", proc.returncode, proc.stderr.strip())
    return f"Scheduled via launchd at {hour:02d}:{minute:02d} — opens a terminal to prompt ({path.name})"


def _remove_launchd(session_id: str) -> str:
    path = _plist_path(session_id)
    launcher = _launcher_path(session_id)
    if not path.exists():
        launcher.unlink(missing_ok=True)
        return "No launchd schedule found."
    subprocess.run(["launchctl", "unload", str(path)], capture_output=True, timeout=10, check=False)
    path.unlink(missing_ok=True)
    launcher.unlink(missing_ok=True)
    logger.info("scheduler[launchd]: removed %s", path)
    return "Removed launchd schedule."


def _status_launchd(session_id: str) -> dict:
    path = _plist_path(session_id)
    return {"platform": "launchd", "installed": path.exists(), "path": str(path)}


# ---------------------------------------------------------------------------
# Linux — crontab
# ---------------------------------------------------------------------------


def _read_crontab() -> list[str]:
    proc = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=10, check=False)
    if proc.returncode != 0:
        # No crontab yet (or error) → treat as empty.
        return []
    return proc.stdout.splitlines()


def _write_crontab(lines: list[str]) -> None:
    content = "\n".join(lines).rstrip("\n") + "\n"
    subprocess.run(["crontab", "-"], input=content, text=True, timeout=10, check=True)


def _cron_marker(session_id: str) -> str:
    return f"{_CRON_MARKER} {session_id}"


def _install_cron(session_id: str, hour: int, minute: int, weekdays: list[int]) -> str:
    marker = _cron_marker(session_id)
    # cron weekday: 0-6 (Sun-Sat) or 1-7; we send Mon-Sun as 1-7 (7 = Sunday, accepted by cron).
    dow = ",".join(str(wd) for wd in weekdays)
    cmd = " ".join(_executable_args(session_id))
    entry = f"{minute} {hour} * * {dow} {cmd} {marker}"

    # Remove any prior block for this session, then append the new one.
    lines = [ln for ln in _read_crontab() if marker not in ln]
    lines.append(entry)
    _write_crontab(lines)
    logger.info("scheduler[cron]: installed entry for %s", session_id)
    return f"Scheduled via crontab at {hour:02d}:{minute:02d}"


def _remove_cron(session_id: str) -> str:
    marker = _cron_marker(session_id)
    lines = _read_crontab()
    kept = [ln for ln in lines if marker not in ln]
    if len(kept) == len(lines):
        return "No crontab schedule found."
    _write_crontab(kept)
    logger.info("scheduler[cron]: removed entry for %s", session_id)
    return "Removed crontab schedule."


def _status_cron(session_id: str) -> dict:
    marker = _cron_marker(session_id)
    installed = any(marker in ln for ln in _read_crontab())
    return {"platform": "cron", "installed": installed, "path": "crontab"}


# ---------------------------------------------------------------------------
# Public API — platform dispatch
# ---------------------------------------------------------------------------


def _is_macos() -> bool:
    return sys.platform == "darwin"


def _is_linux() -> bool:
    return sys.platform.startswith("linux")


def install_schedule(session_id: str, standup_time: str, weekdays: str = "1-5", lead_minutes: int = 10) -> str:
    """Install/replace the OS schedule for a session's standup. Returns a status message.

    ``standup_time`` is when the standup HAPPENS (e.g. "10:00"); the job fires
    ``lead_minutes`` earlier so the summary is delivered before the meeting.
    """
    hour, minute = run_time(standup_time, lead_minutes)  # lead-adjusted fire time
    wd = _weekday_list(weekdays)
    logger.info(
        "install_schedule: session=%s standup=%s lead=%d fire=%02d:%02d weekdays=%s",
        session_id,
        standup_time,
        lead_minutes,
        hour,
        minute,
        weekdays,
    )
    try:
        if _is_macos():
            return _install_launchd(session_id, hour, minute, wd)
        if _is_linux():
            return _install_cron(session_id, hour, minute, wd)
    except (subprocess.SubprocessError, OSError) as e:
        logger.error("install_schedule failed: %s", e)
        return f"Failed to install schedule: {e}"
    return "Scheduling is not supported on this platform — use on-demand standup runs instead."


def remove_schedule(session_id: str) -> str:
    """Remove the OS schedule for a session's standup. Returns a status message."""
    logger.info("remove_schedule: session=%s", session_id)
    try:
        if _is_macos():
            return _remove_launchd(session_id)
        if _is_linux():
            return _remove_cron(session_id)
    except (subprocess.SubprocessError, OSError) as e:
        logger.error("remove_schedule failed: %s", e)
        return f"Failed to remove schedule: {e}"
    return "Scheduling is not supported on this platform."


def get_schedule_status(session_id: str) -> dict:
    """Return {platform, installed, path} describing the current schedule state."""
    try:
        if _is_macos():
            return _status_launchd(session_id)
        if _is_linux():
            return _status_cron(session_id)
    except (subprocess.SubprocessError, OSError) as e:
        logger.warning("get_schedule_status failed: %s", e)
    return {"platform": "unsupported", "installed": False, "path": ""}
