"""Unit tests for Daily Standup Markdown + HTML export."""

from yeaboi.agent.state import MemberUpdate, StandupReport
from yeaboi.standup import export
from yeaboi.standup.export import build_standup_html, build_standup_markdown, export_standup


def _report(**over) -> StandupReport:
    base = dict(
        date="2026-07-10",
        session_id="demo",
        sprint_name="Sprint 5",
        sprint_day=3,
        sprint_total_days=10,
        confidence_pct=82,
        confidence_label="At risk",
        confidence_rationale="behind ideal burn",
        team_summary="steady progress",
        member_updates=(
            MemberUpdate(name="Alice", summary="login page", source="inferred"),
            MemberUpdate(
                name="Bob",
                summary="paired on auth",
                blockers="waiting on review",
                source="combined",
                self_report="paired with Alice on auth",
            ),
        ),
        activity_counts=(("github", 2), ("jira", 1)),
        warnings=("Jira: authentication failed — check token",),
    )
    base.update(over)
    return StandupReport(**base)


class TestMarkdown:
    def test_contains_key_sections(self):
        md = build_standup_markdown(_report())
        assert "# Daily Standup — 2026-07-10" in md
        assert "day 3 of 10" in md
        assert "**Confidence:** At risk (82%)" in md
        assert "## ⚠ Notices" in md
        assert "Jira: authentication failed" in md
        assert "## Team Summary" in md
        # Member updates render as a table (native table on Notion/Confluence).
        assert "| Member | Update | Blocker |" in md
        assert "| **Bob** _(you)_ | paired on auth | waiting on review |" in md
        assert "| **Alice** | login page | — |" in md
        assert "github: 2, jira: 1" in md
        # Branded footer with a real link.
        assert "🤙 _Generated by [yeaboi.ai](https://yeaboi.ai)" in md

    def test_empty_report(self):
        md = build_standup_markdown(StandupReport(date="2026-07-10"))
        assert "# Daily Standup" in md
        assert "_No individual updates._" in md

    def test_images_in_screenshots_section(self):
        md = build_standup_markdown(_report(images=("/tmp/shot1.png", "/tmp/shot2.png")))
        # Screenshots follow the updates table in their own section.
        assert "### Screenshots" in md
        assert "![Screenshot](/tmp/shot1.png)" in md
        assert "![Screenshot](/tmp/shot2.png)" in md

    def test_pipe_in_member_content_sanitized(self):
        rep = _report(member_updates=(MemberUpdate(name="Alice", summary="a | b", source="inferred"),))
        md = build_standup_markdown(rep)
        # A raw pipe would split the table cell.
        assert "| a \\ b |" in md


class TestMemberLinks:
    def test_markdown_links_rendered(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="moved PSOT-1 to review",
                    links=(("PSOT-1", "https://x.atlassian.net/browse/PSOT-1"),),
                ),
            )
        )
        md = build_standup_markdown(rep)
        assert "**Links:** [PSOT-1](https://x.atlassian.net/browse/PSOT-1)" in md

    def test_html_links_are_anchors_and_escaped(self):
        rep = _report(
            member_updates=(
                MemberUpdate(
                    name="Alice",
                    summary="work",
                    links=(("<b>PSOT-1</b>", "https://x.atlassian.net/browse/PSOT-1?a=1&b=2"),),
                ),
            )
        )
        html = build_standup_html(rep)
        assert "<a href='https://x.atlassian.net/browse/PSOT-1?a=1&amp;b=2'" in html
        assert "&lt;b&gt;PSOT-1&lt;/b&gt;" in html  # label escaped, not injected

    def test_no_links_no_section(self):
        md = build_standup_markdown(_report())
        assert "**Links:**" not in md


class TestHtml:
    def test_selfcontained_and_escaped(self):
        rep = _report(team_summary="<script>alert(1)</script>")
        html = build_standup_html(rep)
        assert html.startswith("<!DOCTYPE html>")
        assert "<style>" in html  # inline CSS, self-contained
        assert "data-table" in html
        assert "At risk" in html
        assert "Jira: authentication failed" in html
        # user content is escaped, not injected
        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html

    def test_empty_report(self):
        html = build_standup_html(StandupReport(date="2026-07-10"))
        assert "No individual updates." in html

    def test_images_base64_embedded(self, tmp_path):
        img = tmp_path / "shot.png"
        img.write_bytes(b"\x89PNG fake")
        html = build_standup_html(_report(images=(str(img),)))
        assert "Screenshots" in html
        assert "data:image/png;base64," in html

    def test_missing_image_skipped(self):
        html = build_standup_html(_report(images=("/nope/gone.png",)))
        assert "data:image" not in html


class TestExportWrites:
    def test_writes_md_and_html(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        paths = export_standup(_report(), project_name="My Demo Project")
        assert paths["markdown"].exists() and paths["markdown"].suffix == ".md"
        assert paths["html"].exists() and paths["html"].suffix == ".html"
        # slug of project name is used for the subdir
        assert paths["markdown"].parent.name == "my-demo-project"
        assert "Daily Standup" in paths["markdown"].read_text()
        assert paths["html"].read_text().startswith("<!DOCTYPE html>")

    def test_rerun_same_day_overwrites(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        export_standup(_report(confidence_pct=50), project_name="Demo")
        paths = export_standup(_report(confidence_pct=90), project_name="Demo")
        # one dated file per day, latest wins
        files = list(paths["markdown"].parent.glob("standup-2026-07-10.*"))
        assert len(files) == 2  # .md + .html
        assert "(90%)" in paths["markdown"].read_text()

    def test_slug_helper(self):
        assert export._slug("My Project!!") == "my-project"
        assert export._slug("") == "standup"

    def test_images_localized_into_export_dir(self, tmp_path, monkeypatch):
        monkeypatch.setattr("yeaboi.paths.STANDUP_EXPORTS_DIR", tmp_path / "exports" / "standup")
        img = tmp_path / "shot.png"
        img.write_bytes(b"png")
        paths = export_standup(_report(images=(str(img),)), project_name="Demo")
        md = paths["markdown"].read_text()
        assert "![Screenshot](images/shot.png)" in md
        assert (paths["markdown"].parent / "images" / "shot.png").exists()


class TestSkippedSourcesLine:
    def test_markdown_lists_skipped_sources(self):
        from yeaboi.standup.export import build_standup_markdown

        md = build_standup_markdown(_report(skipped_sources=(("github", "STANDUP_GITHUB_REPO not set"),)))
        assert "Sources skipped — github (STANDUP_GITHUB_REPO not set)" in md

    def test_html_lists_skipped_sources(self):
        from yeaboi.standup.export import build_standup_html

        html = build_standup_html(_report(skipped_sources=(("notion", "NOTION_ROOT_PAGE_ID not set"),)))
        assert "Sources skipped" in html
        assert "NOTION_ROOT_PAGE_ID not set" in html

    def test_plaintext_lists_skipped_sources(self):
        from yeaboi.standup.render import format_standup_plaintext

        text = format_standup_plaintext(_report(skipped_sources=(("confluence", "CONFLUENCE_SPACE_KEY not set"),)))
        assert "Sources skipped — confluence (CONFLUENCE_SPACE_KEY not set)" in text

    def test_no_skipped_sources_no_line(self):
        from yeaboi.standup.render import format_standup_plaintext

        assert "Sources skipped" not in format_standup_plaintext(_report())
