"""Export a RoadmapAnalysis to Markdown + self-contained HTML.

Mirrors the standup / retro / reporting exporters (standup/export.py,
reporting/export.py): readable artifacts written under
``~/.yeaboi/exports/roadmap/<roadmap>/`` so an analyzed roadmap persists as a
shareable document, not just a saved row. Two files per run — a Markdown summary
and a self-contained HTML report (reusing the plan stylesheet
``html_exporter._CSS``). Re-exporting the same roadmap overwrites so the latest
wins.

Every project ``name`` / ``description`` came from an LLM reading an *untrusted*
roadmap document, so the HTML escapes every field with ``html.escape`` — the same
defense the other exporters use. The TUI **Export** button re-writes on demand.

# See docs: "Roadmap Intake" — Export
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from html import escape as _e
from pathlib import Path

from yeaboi.agent.state import RoadmapAnalysis, RoadmapProject

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    """Return a filesystem-safe slug for the export subdirectory."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")[:40] or "roadmap"


def _size_label(project: RoadmapProject) -> str:
    """Human-facing size label ('Large' / 'Small')."""
    return "Large" if getattr(project, "size", "") == "large" else "Small"


def _title(analysis: RoadmapAnalysis) -> str:
    label = (analysis.source_label or "").strip()
    return f"Roadmap — {label}" if label else "Roadmap analysis"


def _meta(project: RoadmapProject) -> str:
    """Return 'Q3 2026 · Theme A, Theme B' (either part optional)."""
    return " · ".join(x for x in (project.quarter, ", ".join(project.themes)) if x)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def build_roadmap_markdown(analysis: RoadmapAnalysis) -> str:
    """Return the roadmap analysis as a Markdown document."""
    when = (analysis.generated_at or "")[:10]
    lines: list[str] = [f"# {_title(analysis)}", ""]
    src = " · ".join(x for x in (analysis.source_type, analysis.source_locator) if x)
    if src:
        lines += [f"**Source:** {src}  "]
    if when:
        lines += [f"**Analyzed:** {when}"]
    lines += [""]
    if analysis.summary:
        lines += [f"> {analysis.summary}", ""]

    if analysis.projects:
        lines += ["## Recommended projects", ""]
        for i, project in enumerate(analysis.projects):
            index = project.priority or (i + 1)
            lines += [f"### {index}. {project.name}  ·  {_size_label(project)}", ""]
            meta = _meta(project)
            if meta:
                lines += [f"_{meta}_", ""]
            if project.description:
                lines += [project.description, ""]
            if project.rationale:
                lines += [f"**Why now:** {project.rationale}", ""]
    else:
        lines += ["_No projects were extracted from the roadmap._", ""]

    if analysis.warnings:
        lines += ["## ⚠ Notices", ""]
        lines += [f"- {w}" for w in analysis.warnings]
        lines += [""]

    lines += ["---", ""]
    lines += [f"🤙 _Generated by [yeaboi.ai](https://yeaboi.ai) · {datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def build_roadmap_html(analysis: RoadmapAnalysis) -> str:
    """Return the roadmap analysis as a self-contained HTML document (reuses plan CSS)."""
    from yeaboi.html_exporter import _CSS

    when = (analysis.generated_at or "")[:10]
    parts: list[str] = ['<div class="container">', f"<h1>{_e(_title(analysis))}</h1>"]
    src = " &bull; ".join(_e(x) for x in (analysis.source_type, analysis.source_locator) if x)
    sub = " &bull; ".join(x for x in (src, f"analyzed {_e(when)}" if when else "") if x)
    if sub:
        parts.append(f"<p style='color:var(--text-muted)'>{sub}</p>")
    if analysis.summary:
        parts.append(f"<blockquote><strong>{_e(analysis.summary)}</strong></blockquote>")

    if analysis.projects:
        parts.append("<h2>Recommended projects</h2>")
        for i, project in enumerate(analysis.projects):
            index = project.priority or (i + 1)
            badge_bg = "#8a6d1a" if getattr(project, "size", "") == "large" else "#1a6d3a"
            badge = (
                f"<span style='background:{badge_bg};color:#fff;border-radius:6px;"
                f"padding:.05rem .5rem;font-size:.8rem;margin-left:.5rem'>{_e(_size_label(project))}</span>"
            )
            parts.append(f"<h3>{index}. {_e(project.name)}{badge}</h3>")
            meta = _meta(project)
            if meta:
                parts.append(f"<p style='color:var(--text-muted);font-size:.9rem'>{_e(meta)}</p>")
            if project.description:
                parts.append(f"<p>{_e(project.description).replace(chr(10), '<br>')}</p>")
            if project.rationale:
                parts.append(f"<p><strong>Why now:</strong> {_e(project.rationale)}</p>")
    else:
        parts.append("<p><em>No projects were extracted from the roadmap.</em></p>")

    if analysis.warnings:
        items = "".join(f"<li>{_e(w)}</li>" for w in analysis.warnings)
        parts.append(f"<h2>⚠ Notices</h2><ul>{items}</ul>")
    parts.append("</div>")
    body = "".join(parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{_e(_title(analysis))}</title>
  <style>{_CSS}</style>
</head>
<body>
{body}
<footer class="site-footer">
  Generated by yeaboi.ai &bull; {_e(datetime.now().strftime("%Y-%m-%d"))}
</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Write helper
# ---------------------------------------------------------------------------


def export_roadmap(analysis: RoadmapAnalysis, *, name: str = "") -> dict[str, Path]:
    """Write the analysis as Markdown + HTML under the roadmap export dir.

    Returns ``{"markdown": Path, "html": Path}``. ``name`` (the roadmap's friendly
    label) picks the sub-directory; re-exporting overwrites so the latest wins.
    """
    from yeaboi.paths import get_roadmap_export_dir

    key = _slug(name or analysis.source_label or "roadmap")
    out_dir = get_roadmap_export_dir(key)
    stem = f"roadmap-{key}"
    md_path = out_dir / f"{stem}.md"
    html_path = out_dir / f"{stem}.html"
    md_path.write_text(build_roadmap_markdown(analysis), encoding="utf-8")
    html_path.write_text(build_roadmap_html(analysis), encoding="utf-8")
    logger.info("Roadmap exported: %s , %s", md_path, html_path)
    return {"markdown": md_path, "html": html_path}
